sed -i 's/\t0$/\tacrisols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t1$/\talbeluvisols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t2$/\talisols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t3$/\tandosols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t4$/\tarenosols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t5$/\tcalcisols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t6$/\tcambisols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t7$/\tchernozems/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t8$/\tcryosols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t9$/\tdurisols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t10$/\tferralsols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t11$/\tfluvisols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t12$/\tgleysols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t13$/\tgypsisols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t14$/\thistosols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t15$/\tkastanozems/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t16$/\tleptosols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t17$/\tlixisols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t18$/\tluvisols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t19$/\tnitisols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t20$/\tphaeozems/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t21$/\tplanosols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t22$/\tplinthosols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t23$/\tpodzols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t24$/\tregosols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t25$/\tsolonchaks/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t26$/\tsolonetz/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t27$/\tstagnosols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t28$/\tumbrisols/g' soiltype_mostprobable.mode.renamed.csv
sed -i 's/\t29$/\tvertisols/g' soiltype_mostprobable.mode.renamed.csv